const tg = window.Telegram?.WebApp;
tg?.ready(); tg?.expand();
const initData = tg?.initData || "";
const telegramUser = tg?.initDataUnsafe?.user;
const userId = telegramUser?.id || 1;
const headers = () => ({"X-Telegram-Init-Data": initData, "X-Debug-User-ID": String(userId)});
let selectedPhoto = null;
let selectedLabel = null;
let latestMeals = [];
let currentBarcodeProduct = null;

const $ = id => document.getElementById(id);
const toast = text => { $("toast").textContent=text; $("toast").classList.add("show"); setTimeout(()=>$("toast").classList.remove("show"),2600); };
async function api(path, options={}) {
  options.headers = {...headers(), ...(options.headers||{})};
  const response = await fetch(path, {...options, cache:"no-store"});
  if (!response.ok) {
    let detail = response.status >= 500 ? "Сервер временно недоступен. Повтори попытку позже." : "Не удалось выполнить запрос";
    try {
      const body = await response.json();
      if (typeof body.detail === "string") detail = body.detail;
      else if (Array.isArray(body.detail)) detail = "Проверь заполнение полей и допустимые значения";
    } catch {}
    throw new Error(detail);
  }
  return response.json();
}
function switchView(id){ document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id)); document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id)); window.scrollTo({top:0,behavior:"smooth"}); if(id==="todayView")loadDashboard(); if(id==="profileView")loadProgress(); if(id==="coachView")Promise.all([loadInsights(),loadReminders()]); if(id==="toolsView")loadTools(); if(id==="adminView")loadAdmin(); }
document.querySelectorAll("nav button").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));
$("profileShortcut").onclick=()=>switchView("profileView");
document.querySelectorAll("[data-close-dialog]").forEach(button => {
  button.onclick = () => button.closest("dialog").close();
});

function fillTargets(p){
  $("kcalTarget").textContent=p.targets.calories; $("proteinTarget").textContent=p.targets.protein; $("fatTarget").textContent=p.targets.fat; $("carbsTarget").textContent=p.targets.carbs;
  $("targetCard").style.display="block"; $("targetCard").innerHTML=`<strong>${p.targets.calories} ккал</strong><p>Белки ${p.targets.protein} г · Жиры ${p.targets.fat} г · Углеводы ${p.targets.carbs} г</p><small>Поддержание: ${p.targets.maintenance_kcal} ккал · Профицит: +${p.targets.surplus}</small>`;
}
async function loadDashboard(){
  try{
    const d=await api("/api/dashboard");
    $("greeting").textContent=`Баланс, ${d.profile.name}`; $("kcalNow").textContent=Math.round(d.totals.kcal); fillTargets(d.profile);
    $("calorieRing").style.setProperty("--p",d.progress.kcal); $("remainingText").textContent=d.remaining.kcal?`До цели осталось ${d.remaining.kcal} ккал и ${d.remaining.protein} г белка`:`Цель по калориям на сегодня выполнена`;
    for(const key of ["protein","fat","carbs"]){ $(`${key}Now`).textContent=Math.round(d.totals[key]); $(`${key}Bar`).style.width=`${d.progress[key]}%`; }
    $("budgetInput").value=d.profile.weekly_budget;
    latestMeals=d.meals;
    $("mealList").innerHTML=d.meals.length?d.meals.map(m=>`<article class="meal"><div><h4>${escapeHtml(m.name)}</h4><p>${escapeHtml(m.meal_type)} · ${Math.round(m.grams)} г · Б ${Math.round(m.protein)} / Ж ${Math.round(m.fat)} / У ${Math.round(m.carbs)}</p></div><strong>${Math.round(m.kcal)} ккал</strong><div class="meal-actions"><button class="favorite-meal" data-id="${m.id}">В избранное</button><button class="edit-meal" data-id="${m.id}">Изменить</button><button class="delete-meal" data-id="${m.id}">Удалить</button></div></article>`).join(""):`<p class="empty">Пока нет записей. Добавь фотографию первого блюда.</p>`;
    document.querySelectorAll(".favorite-meal").forEach(button=>button.onclick=()=>saveMealFavorite(latestMeals.find(m=>m.id===Number(button.dataset.id))));
    document.querySelectorAll(".edit-meal").forEach(button=>button.onclick=()=>editMeal(latestMeals.find(m=>m.id===Number(button.dataset.id))));
    document.querySelectorAll(".delete-meal").forEach(button=>button.onclick=()=>deleteMeal(Number(button.dataset.id)));
    if(d.latest_plan)renderPlan(d.latest_plan);
  }catch(e){ if(e.message.includes("Профиль")){switchView("profileView");toast("Сначала заполни профиль");}else toast(e.message); }
}
function escapeHtml(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML;}
window.deleteMeal=async id=>{try{await api(`/api/meals/${id}`,{method:"DELETE"});loadDashboard();}catch(e){toast(e.message)}};
function editMeal(meal){const f=$("editForm");for(const [key,value] of Object.entries(meal))if(f.elements[key])f.elements[key].value=value;$("editDialog").showModal();}
async function saveMealFavorite(meal){try{await api("/api/favorites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_user_id:userId,name:meal.name,meal_type:meal.meal_type,grams:meal.grams,kcal:meal.kcal,protein:meal.protein,fat:meal.fat,carbs:meal.carbs})});toast("Блюдо добавлено в избранное");}catch(e){toast(e.message)}}

$("photoInput").onchange=e=>{selectedPhoto=e.target.files[0];if(!selectedPhoto)return;const img=$("photoPreview");img.src=URL.createObjectURL(selectedPhoto);img.style.display="block";$("analyzeButton").disabled=false;};
$("analyzeButton").onclick=async()=>{
  const b=$("analyzeButton"),old=b.textContent;b.disabled=true;b.innerHTML='<i class="loader"></i>AI анализирует фото';
  const form=new FormData();form.append("telegram_user_id",userId);form.append("meal_type",$("mealType").value);form.append("save","false");form.append("image",selectedPhoto);
  try{const r=await api("/api/meals/photo",{method:"POST",body:form}),a=r.analysis,f=$("photoConfirmForm");f.elements.name.value=a.dish_name;f.elements.grams.value=Math.round(a.total_grams);f.elements.kcal.value=Math.round(a.total_kcal);f.elements.protein.value=a.total_protein;f.elements.fat.value=a.total_fat;f.elements.carbs.value=a.total_carbs;f.elements.confidence.value=a.confidence;$("photoConfirmNote").textContent=(a.assumptions||[]).slice(0,3).join(" · ")||"Исправь неточности перед записью в дневник.";$("photoConfirmDialog").showModal();}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent=old;}
};
$("photoConfirmForm").addEventListener("submit",async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));for(const key of ["grams","kcal","protein","fat","carbs","confidence"])data[key]=Number(data[key]);data.telegram_user_id=userId;data.meal_type=$("mealType").value;try{const meal=await api("/api/meals/photo/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});$("photoConfirmDialog").close();$("analysisResult").innerHTML=`<article class="analysis-card"><h3>${escapeHtml(meal.name)}</h3><strong>${Math.round(meal.kcal)} ккал</strong><p>Б ${Math.round(meal.protein)} · Ж ${Math.round(meal.fat)} · У ${Math.round(meal.carbs)} г · ${Math.round(meal.grams)} г</p><small>Проверено и записано в дневник</small></article>`;toast("Блюдо записано после проверки");}catch(e){toast(e.message)}});

async function lookupBarcode(){const code=$("barcodeInput").value.replace(/\D/g,"");if(code.length<8)return toast("Введи от 8 до 14 цифр штрихкода");const button=$("barcodeButton"),old=button.textContent;button.disabled=true;button.textContent="Ищу…";try{const p=await api(`/api/barcode/${code}`);currentBarcodeProduct=p;const complete=[p.kcal_per_100g,p.protein_per_100g,p.fat_per_100g,p.carbs_per_100g].every(v=>v!=null),image=p.image_url?`<img src="${escapeHtml(p.image_url)}" alt="">`:"";$("barcodeResult").innerHTML=`${image}<h4>${escapeHtml(p.name)}</h4><p>${escapeHtml(p.brand)} ${escapeHtml(p.quantity)}<br>На 100 г: <b>${p.kcal_per_100g??'—'} ккал</b> · Б ${p.protein_per_100g??'—'} · Ж ${p.fat_per_100g??'—'} · У ${p.carbs_per_100g??'—'}</p><label>Моя порция, г<input id="barcodeGrams" type="number" min="1" max="5000" value="100"></label><button class="primary" id="barcodeAdd" ${complete?'':'disabled'}>${complete?'Добавить в дневник':'На упаковке нет полного КБЖУ'}</button><p>Источник: Open Food Facts. Всегда сверяй цифры с упаковкой.</p>`;if(complete)$("barcodeAdd").onclick=addBarcodeMeal;}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent=old;}}
async function addBarcodeMeal(){const grams=Number($("barcodeGrams").value),p=currentBarcodeProduct;if(!p||!Number.isFinite(grams)||grams<=0)return toast("Укажи вес порции");const factor=grams/100,data={telegram_user_id:userId,name:p.name,meal_type:"Продукт",grams,kcal:p.kcal_per_100g*factor,protein:p.protein_per_100g*factor,fat:p.fat_per_100g*factor,carbs:p.carbs_per_100g*factor};try{await api("/api/meals/manual",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});toast("Продукт добавлен в дневник");$("barcodeResult").innerHTML="";}catch(e){toast(e.message)}}
$("barcodeButton").onclick=lookupBarcode;
$("barcodeInput").addEventListener("keydown",event=>{if(event.key==="Enter")lookupBarcode();});
$("barcodeImage").onchange=async event=>{const file=event.target.files[0];if(!file)return;$("barcodeFileName").textContent=file.name;if(!("BarcodeDetector" in window))return toast("На этом телефоне введи цифры штрихкода вручную");try{const detector=new BarcodeDetector({formats:["ean_13","ean_8","upc_a","upc_e"]}),bitmap=await createImageBitmap(file),codes=await detector.detect(bitmap);bitmap.close();if(!codes.length)return toast("Штрихкод не найден — сделай фото ближе");$("barcodeInput").value=codes[0].rawValue;lookupBarcode();}catch{toast("Не удалось считать штрихкод. Введи цифры вручную")}};

$("manualOpen").onclick=()=>$("manualDialog").showModal();
$("manualForm").addEventListener("submit",async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));for(const k of ["grams","kcal","protein","fat","carbs"])x[k]=Number(x[k]);x.telegram_user_id=userId;x.meal_type="Вручную";try{await api("/api/meals/manual",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(x)});$("manualDialog").close();e.target.reset();loadDashboard();}catch(err){toast(err.message)}});
$("editForm").addEventListener("submit",async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));const mealId=Number(x.meal_id);delete x.meal_id;for(const k of ["grams","kcal","protein","fat","carbs"])x[k]=Number(x[k]);x.telegram_user_id=userId;try{await api(`/api/meals/${mealId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(x)});$("editDialog").close();toast("Оценка исправлена");loadDashboard();}catch(err){toast(err.message)}});

$("profileForm").addEventListener("submit",async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));for(const k of ["age","height_cm","weight_kg","target_weight_kg","meals_per_day","weekly_budget"])x[k]=Number(x[k]);x.telegram_user_id=userId;try{const p=await api("/api/profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(x)});fillTargets(p);toast("Профиль и цель сохранены");}catch(err){toast(err.message)}});
async function loadProfile(){try{const p=await api("/api/profile");for(const [k,v] of Object.entries(p)){const el=$("profileForm").elements[k];if(el)el.value=v;}fillTargets(p);}catch{}}

$("planButton").onclick=async()=>{const b=$("planButton"),old=b.textContent;b.disabled=true;b.innerHTML='<i class="loader"></i>Составляю 7 дней';try{const p=await api("/api/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_user_id:userId,budget:Number($("budgetInput").value),pantry:$("pantryInput").value,wishes:$("wishesInput").value})});renderPlan(p);toast("Рацион готов");}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent=old;}};
function renderPlan(p){
  const days=p.days.map(d=>`<article class="day-card"><h3>${escapeHtml(d.day)}</h3><p>${d.total_kcal} ккал · Б ${d.total_protein} · Ж ${d.total_fat} · У ${d.total_carbs}</p>${d.meals.map(m=>`<details><summary>${escapeHtml(m.meal_type)} — ${escapeHtml(m.dish)}</summary><p><b>${m.kcal} ккал</b><br>${m.ingredients.map(escapeHtml).join(", ")}<br><br>${escapeHtml(m.recipe)}</p></details>`).join("")}</article>`).join("");
  const groceries=p.groceries.map(g=>`<div class="grocery-row"><div><b>${escapeHtml(g.name)}</b><br><span>${escapeHtml(g.quantity)}</span></div><strong>≈ ${g.estimated_price} ₽</strong></div>`).join("");
  $("planResult").innerHTML=`<article class="plan-summary"><h3>${escapeHtml(p.title)}</h3><p>Расчётная корзина: <b>${p.estimated_total} ₽</b> из ${p.budget} ₽</p><small>Цены ориентировочные и зависят от магазина.</small></article>${days}<article class="grocery-card"><h3>Список покупок</h3>${groceries}</article><article class="grocery-card"><h3>План готовки</h3><ol>${p.prep_plan.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ol></article>`;
}

const adviceHints={top_up:"Дневник уже содержит нужные данные",review:"AI проверит сегодняшний рацион",recipe:"Например: творог, банан, яйца",swap:"Например: заменить овсянку без молока",portion:"Например: рис с курицей",coach:"Например: почему вес не растёт вторую неделю?"};
function updateAdviceMode(){const mode=$("adviceMode").value,needsQuery=!['top_up','review'].includes(mode);$("adviceQueryWrap").style.display=needsQuery?'grid':'none';$("adviceQuery").placeholder=adviceHints[mode];}
$("adviceMode").onchange=updateAdviceMode;updateAdviceMode();
function renderAdvice(result,target="adviceResult"){const note=result.note?`<p>${escapeHtml(result.note)}</p>`:"";$(target).innerHTML=`<h4>${escapeHtml(result.title)}</h4><p>${escapeHtml(result.summary)}</p><ul>${result.recommendations.map(item=>`<li>${escapeHtml(item)}</li>`).join("")}</ul>${note}`;}
$("adviceButton").onclick=async()=>{const button=$("adviceButton"),old=button.textContent,mode=$("adviceMode").value;button.disabled=true;button.innerHTML='<i class="loader"></i>AI анализирует';try{const result=await api("/api/advice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_user_id:userId,mode,query:$("adviceQuery").value})});renderAdvice(result);}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent=old;}};

async function loadInsights(){try{const data=await api("/api/insights"),week=data.week,forecast=data.forecast,game=data.gamification;$("streakValue").textContent=data.streak_days;$("weekValue").textContent=`${week.days_logged}/7`;$("weekDetails").textContent=`${week.days_on_target} дн. около нормы · в среднем ${Math.round(week.averages.kcal)} ккал`;$("forecastTitle").textContent=forecast.status==='achieved'?'Цель достигнута':forecast.weekly_rate?`${forecast.weekly_rate>0?'+':''}${forecast.weekly_rate} кг в неделю`:'Набираем данные';$("forecastText").textContent=forecast.message;$("achievementList").innerHTML=data.achievements.length?data.achievements.map(item=>`<span class="achievement" title="${escapeHtml(item.text)}">✓ ${escapeHtml(item.title)}</span>`).join(""):'<span class="achievement">Первое достижение уже близко</span>';$("levelTitle").textContent=`Уровень ${game.level} · ${game.level_name}`;$("levelText").textContent=`${game.points} баллов · ${game.level>=20?'максимальный уровень':`${game.next_level_points-game.points} до следующего`}`;$("levelProgress").style.width=`${game.progress_percent}%`;}catch(e){toast(e.message)}}

$("labelInput").onchange=event=>{selectedLabel=event.target.files[0];$("labelFileName").textContent=selectedLabel?.name||"Файл не выбран";$("labelButton").disabled=!selectedLabel;};
$("labelButton").onclick=async()=>{const button=$("labelButton"),old=button.textContent;button.disabled=true;button.innerHTML='<i class="loader"></i>Читаю этикетку';const form=new FormData();form.append("image",selectedLabel);try{const result=await api("/api/label",{method:"POST",body:form}),value=x=>x??'—';$("labelResult").innerHTML=`<h4>${escapeHtml(result.product_name)}</h4><p>На 100 г: <b>${value(result.kcal_per_100g)} ккал</b> · Б ${value(result.protein_per_100g)} · Ж ${value(result.fat_per_100g)} · У ${value(result.carbs_per_100g)}</p><p>Порция: ${escapeHtml(result.serving)}<br>Аллергены: ${result.allergens.length?result.allergens.map(escapeHtml).join(', '):'не указаны'}</p><ul>${result.notes.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`;}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent=old;}};

async function loadReminders(){try{const data=await api("/api/reminders"),form=$("reminderForm");for(const [key,value] of Object.entries(data)){const field=form.elements[key];if(!field)continue;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=value;}form.elements.timezone.value=Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Moscow';}catch(e){toast(e.message)}}
$("reminderForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.target,data=Object.fromEntries(new FormData(form));for(const key of ['enabled','meal_reminders','weigh_reminder','weekly_report'])data[key]=form.elements[key].checked;data.telegram_user_id=userId;data.weigh_weekday=Number(data.weigh_weekday);data.timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Moscow';try{await api("/api/reminders",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});toast(data.enabled?'Напоминания включены':'Напоминания сохранены и выключены');}catch(e){toast(e.message)}});

$("weightSave").onclick=async()=>{
  const input=$("weightInput"), button=$("weightSave"), weight=Number(input.value.replace(",","."));
  if(!Number.isFinite(weight)||weight<35||weight>300)return toast("Укажи вес от 35 до 300 кг");
  button.disabled=true;
  try{
    await api("/api/weight",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_user_id:userId,weight_kg:weight})});
    $("profileForm").elements.weight_kg.value=weight; input.value="";
    toast(`Вес ${weight} кг записан`); await Promise.all([loadProfile(),loadProgress()]);
  }catch(e){toast(e.message)}finally{button.disabled=false;}
};
async function loadProgress(){try{const d=await api("/api/progress"),history=$("weightHistory"),current=$("weightCurrent");if(!d.weights.length){current.textContent="История веса пока пуста";history.innerHTML="";return;}const values=d.weights.map(x=>x.weight_kg),min=Math.min(...values)-1,max=Math.max(...values)+1,last=d.weights[d.weights.length-1],dateText=new Date(`${last.measured_on}T00:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long"});current.innerHTML=`Текущий вес <strong>${last.weight_kg} кг</strong><span>${dateText}</span>`;history.innerHTML=d.weights.map(x=>{const shortDate=new Date(`${x.measured_on}T00:00:00`).toLocaleDateString("ru-RU",{day:"2-digit",month:"2-digit"}),height=30+(x.weight_kg-min)/(max-min)*45;return `<div class="weight-point" title="${x.measured_on}: ${x.weight_kg} кг" style="height:${height}px"><strong>${x.weight_kg} кг</strong><span>${shortDate}</span></div>`;}).join("");}catch(e){toast(e.message)}}

const adminEventNames={bot_start:"Запуск бота",profile_saved:"Профиль сохранён",meal_manual:"Еда добавлена вручную",meal_photo_confirmed:"Фото подтверждено",meal_corrected:"Запись еды исправлена",meal_deleted:"Запись еды удалена",favorite_saved:"Блюдо сохранено",favorite_used:"Избранное добавлено",water_added:"Вода записана",workout_added:"Тренировка записана",measurement_saved:"Замеры сохранены",progress_photo_added:"Фото прогресса",feedback_sent:"Получена обратная связь",barcode_lookup:"Поиск по штрихкоду",admin_user_control:"Изменён доступ",admin_broadcast:"Выполнена рассылка",weight_saved:"Вес записан",reminders_saved:"Напоминания изменены",ai_photo:"AI распознал блюдо",ai_plan:"AI составил рацион",ai_advice:"AI подготовил совет",ai_label:"AI прочитал этикетку"};
function adminDate(value){if(!value)return "—";const date=new Date(value);return Number.isNaN(date.getTime())?"—":date.toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}
function formatBytes(value){if(value<1024)return `${value} Б`;if(value<1024*1024)return `${Math.round(value/1024)} КБ`;return `${(value/1024/1024).toFixed(1)} МБ`;}
function renderAdminOverview(data){
  const m=data.metrics,r=data.runtime;
  const metrics=[
    ["Всего пользователей",m.total_users],["Активны сегодня",m.active_today],
    ["Активны за 7 дней",m.active_7d],["Блюд сегодня",m.meals_today],
    ["AI-запросов за 7 дней",m.ai_requests_7d],["Ошибок AI за 7 дней",m.ai_errors_7d],
    ["Всего блюд",m.meals_total],["Планов питания",m.plans_total],
    ["Записей веса",m.weights_total],["Включили напоминания",m.reminders_enabled],
    ["Воды сегодня",`${m.water_today_ml} мл`],["Тренировок за 7 дней",m.workouts_7d],
    ["Новых обращений",m.feedback_new],["Заблокировано",m.blocked_users],
  ];
  $("adminMetrics").innerHTML=metrics.map(([label,value])=>`<article class="admin-metric"><span>${escapeHtml(label)}</span><strong>${value}</strong></article>`).join("");
  const healthy=r.bot_polling==='active'&&r.ai_configured;
  $("adminStatusTitle").textContent=healthy?"Все сервисы работают":"Нужна проверка настроек";
  $("adminStatusText").textContent=`Версия ${r.version} · порт ${r.port} · база ${formatBytes(data.database_size_bytes)}`;
  $("adminStatusDot").style.background=healthy?'#b9f24a':'#ff956b';
  const runtime=[["Telegram-бот",r.bot_polling],["OpenAI",r.ai_configured?'подключён':'не подключён'],["Публичный доступ",r.public_access?'включён':'выключен'],["Версия",r.version]];
  $("adminRuntime").innerHTML=runtime.map(([label,value])=>`<div class="runtime-item"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join("");
  const maxValue=Math.max(1,...data.trend.flatMap(item=>[item.active_users,item.ai_requests]));
  $("adminTrend").innerHTML=data.trend.map(item=>{const day=new Date(`${item.day}T00:00:00`).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'}),active=3+item.active_users/maxValue*98,ai=3+item.ai_requests/maxValue*98;return `<div class="trend-day" title="${day}: активных ${item.active_users}, AI ${item.ai_requests}"><div class="trend-bars"><i class="trend-active" style="height:${active}px"></i><i class="trend-ai" style="height:${ai}px"></i></div><small>${day.slice(0,2)}</small></div>`;}).join("");
  $("adminEvents").innerHTML=data.recent_events.length?data.recent_events.map(item=>`<div class="admin-event ${item.status==='error'?'error':''}"><i class="event-mark"></i><div><strong>${escapeHtml(adminEventNames[item.event_type]||item.event_type)}</strong><p>ID ${item.telegram_user_id??'—'}${item.detail?` · ${escapeHtml(item.detail)}`:''}</p></div><time>${adminDate(item.created_at)}</time></div>`).join(""):'<p class="admin-empty">Событий пока нет. Они появятся после действий пользователей.</p>';
}
function renderAdminUsers(data){
  $("adminUsersCount").textContent=`Найдено: ${data.total}`;
  $("adminUsers").innerHTML=data.items.length?data.items.map(item=>`<article class="admin-user"><div class="admin-user-head"><div><h4>${escapeHtml(item.name)} ${item.blocked?'· заблокирован':''}</h4><code>Telegram ID ${item.telegram_user_id}</code></div><span class="admin-user-time">${adminDate(item.last_activity)}</span></div><div class="admin-user-stats"><span>${item.meals_count} блюд</span><span>${item.ai_requests} AI</span><span>${item.workouts_count} тренировок</span><span>${item.plans_count} планов</span>${item.weight_kg!=null?`<span>${item.weight_kg} → ${item.target_weight_kg} кг</span>`:''}${item.reminders_enabled?'<span>Напоминания ✓</span>':''}</div><div class="user-control-row"><button class="user-detail" data-id="${item.telegram_user_id}">Подробнее</button><button class="toggle-block ${item.blocked?'':'block'}" data-id="${item.telegram_user_id}" data-blocked="${item.blocked}">${item.blocked?'Разблокировать':'Заблокировать'}</button></div></article>`).join(""):'<p class="admin-empty">Пользователи не найдены.</p>';
  document.querySelectorAll(".toggle-block").forEach(button=>button.onclick=()=>toggleUserBlock(Number(button.dataset.id),button.dataset.blocked!=="true"));
  document.querySelectorAll(".user-detail").forEach(button=>button.onclick=()=>showUserDetail(Number(button.dataset.id)));
}
function renderAdminFeedback(data){$("adminFeedback").innerHTML=data.items.length?data.items.map(item=>`<article class="admin-feedback-item"><h4>ID ${item.telegram_user_id} · версия ${escapeHtml(item.app_version)}</h4><p>${escapeHtml(item.message)}</p><small>${adminDate(item.created_at)} · ${item.status==='resolved'?'обработано':'новое'}</small><div class="admin-feedback-actions">${item.has_screenshot?`<button data-feedback-screenshot="${item.id}">Скриншот</button>`:''}${item.status!=='resolved'?`<button data-feedback="${item.id}">Отметить решённым</button>`:''}</div></article>`).join(""):'<p class="admin-empty">Новых сообщений нет.</p>';document.querySelectorAll("[data-feedback]").forEach(button=>button.onclick=async()=>{try{await api(`/api/admin/feedback/${button.dataset.feedback}`,{method:"PATCH"});loadAdmin();}catch(e){toast(e.message)}});document.querySelectorAll("[data-feedback-screenshot]").forEach(button=>button.onclick=()=>viewFeedbackScreenshot(button.dataset.feedbackScreenshot));}
async function toggleUserBlock(id,blocked){if(!confirm(blocked?`Заблокировать пользователя ${id}?`:`Разблокировать пользователя ${id}?`))return;const note=blocked?(prompt("Причина блокировки (необязательно)")||""):"";try{await api(`/api/admin/users/${id}/control`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({blocked,note})});toast(blocked?"Пользователь заблокирован":"Доступ восстановлен");loadAdmin();}catch(e){toast(e.message)}}
async function showUserDetail(id){try{const data=await api(`/api/admin/users/${id}`),p=data.profile,meals=data.recent_meals.map(item=>`${item.eaten_on}: ${item.name} — ${Math.round(item.kcal)} ккал`).join("\n")||"Записей пока нет";alert(`${p?.name||'Без профиля'} · ID ${id}\nВес: ${p?.weight_kg??'—'} → ${p?.target_weight_kg??'—'} кг\nГород: ${p?.city||'—'}\n\nПоследние блюда:\n${meals}`);}catch(e){toast(e.message)}}
async function loadAdmin(){
  try{const search=$("adminSearch").value.trim(),audience=$("broadcastForm").elements.audience.value,[overview,users,feedback,estimate]=await Promise.all([api("/api/admin/overview"),api(`/api/admin/users?search=${encodeURIComponent(search)}`),api("/api/admin/feedback"),api(`/api/admin/broadcast/estimate?audience=${audience}`)]);renderAdminOverview(overview);renderAdminUsers(users);renderAdminFeedback(feedback);$("broadcastEstimate").textContent=`Получателей: ${estimate.recipients}`;}catch(e){toast(e.message)}
}
async function discoverAdmin(){
  try{await api("/api/admin/session");$("adminNav").classList.remove("hidden");$("mainNav").classList.add("admin-nav-enabled");if(location.hash==="#admin")switchView("adminView");}catch{}
}
$("adminRefresh").onclick=loadAdmin;
$("adminSearchForm").addEventListener("submit",event=>{event.preventDefault();loadAdmin();});

function renderFavorites(data){$("favoriteList").innerHTML=data.items.length?data.items.map(item=>`<article class="compact-item"><div><h4>${escapeHtml(item.name)}</h4><p>${Math.round(item.kcal)} ккал · Б ${Math.round(item.protein)} / Ж ${Math.round(item.fat)} / У ${Math.round(item.carbs)}</p></div><div><button data-favorite-use="${item.id}">Добавить</button><button class="danger" data-favorite-delete="${item.id}">×</button></div></article>`).join(""):'<p class="admin-empty">Нажми «В избранное» у блюда в дневнике.</p>';document.querySelectorAll("[data-favorite-use]").forEach(button=>button.onclick=async()=>{try{await api(`/api/favorites/${button.dataset.favoriteUse}/use`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_user_id:userId})});toast("Блюдо добавлено на сегодня");}catch(e){toast(e.message)}});document.querySelectorAll("[data-favorite-delete]").forEach(button=>button.onclick=async()=>{try{await api(`/api/favorites/${button.dataset.favoriteDelete}`,{method:"DELETE"});loadTools();}catch(e){toast(e.message)}});}
function renderWater(data){$("waterValue").textContent=`${data.total_ml} мл`;$("waterTargetText").textContent=`Цель ${data.target_ml} мл · осталось ${Math.max(0,data.target_ml-data.total_ml)} мл`;$("waterBar").style.width=`${Math.min(100,data.total_ml/data.target_ml*100)}%`;$("waterEntries").innerHTML=data.entries.length?data.entries.map(item=>`<article class="compact-item"><div><h4>+${item.ml} мл</h4><p>${adminDate(item.created_at)}</p></div><button class="danger" data-water-delete="${item.id}">Удалить</button></article>`).join(""):"";document.querySelectorAll("[data-water-delete]").forEach(button=>button.onclick=async()=>{try{await api(`/api/water/${button.dataset.waterDelete}`,{method:"DELETE"});loadTools();}catch(e){toast(e.message)}});}
function renderWorkouts(data){$("workoutList").innerHTML=data.items.length?data.items.slice(0,10).map(item=>`<article class="compact-item"><div><h4>${escapeHtml(item.name)} · ${item.duration_minutes} мин</h4><p>${item.performed_on}${item.notes?` · ${escapeHtml(item.notes)}`:''}</p></div><button class="danger" data-workout-delete="${item.id}">×</button></article>`).join(""):'<p class="admin-empty">Первая тренировка появится здесь.</p>';document.querySelectorAll("[data-workout-delete]").forEach(button=>button.onclick=async()=>{try{await api(`/api/workouts/${button.dataset.workoutDelete}`,{method:"DELETE"});loadTools();}catch(e){toast(e.message)}});}
function renderMeasurements(data){$("measurementHistory").innerHTML=data.items.length?data.items.map(item=>{const values=[["Г",item.chest_cm],["Т",item.waist_cm],["Б",item.hips_cm],["Р",item.arm_cm],["Н",item.thigh_cm]].filter(x=>x[1]!=null).map(x=>`${x[0]} ${x[1]}`).join(" · ");return `<article class="measurement-chip"><strong>${item.measured_on}</strong><p>${values} см</p></article>`;}).join(""):'<p class="admin-empty">Замеров пока нет.</p>';}
async function protectedBlob(path){const response=await fetch(path,{headers:headers(),cache:"no-store"});if(!response.ok)throw new Error("Файл недоступен");return response.blob();}
async function renderProgressPhotos(data){$("progressPhotoGallery").innerHTML=data.items.map(item=>`<article class="progress-photo"><img data-progress-image="${item.id}" alt="Фото от ${item.taken_on}"><time>${item.taken_on}</time><button data-photo-delete="${item.id}">×</button></article>`).join("");for(const image of document.querySelectorAll("[data-progress-image]")){try{image.src=URL.createObjectURL(await protectedBlob(`/api/progress-photos/${image.dataset.progressImage}`));}catch{image.alt="Не удалось загрузить";}}document.querySelectorAll("[data-photo-delete]").forEach(button=>button.onclick=async()=>{if(!confirm("Удалить эту фотографию?"))return;try{await api(`/api/progress-photos/${button.dataset.photoDelete}`,{method:"DELETE"});loadTools();}catch(e){toast(e.message)}});}
function renderShopping(data){$("shoppingDone").textContent=`${data.checked_total} ₽`;$("shoppingTotal").textContent=`из ${data.total} ₽`;$("shoppingList").innerHTML=data.items.length?data.items.map(item=>`<label class="shopping-item ${item.checked?'checked':''}"><input type="checkbox" data-shopping="${item.id}" ${item.checked?'checked':''}><div><b>${escapeHtml(item.name)}</b><p>${escapeHtml(item.quantity)}</p></div><strong>≈ ${item.estimated_price} ₽</strong></label>`).join(""):'<p class="admin-empty">Сначала создай рацион на неделю.</p>';document.querySelectorAll("[data-shopping]").forEach(input=>input.onchange=async()=>{try{const result=await api(`/api/shopping/${input.dataset.shopping}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_user_id:userId,checked:input.checked})});renderShopping(result);}catch(e){toast(e.message)}});}
async function loadTools(){try{const [favorites,water,workouts,measurements,photos,shopping]=await Promise.all([api("/api/favorites"),api("/api/water"),api("/api/workouts"),api("/api/measurements"),api("/api/progress-photos"),api("/api/shopping")]);renderFavorites(favorites);renderWater(water);renderWorkouts(workouts);renderMeasurements(measurements);await renderProgressPhotos(photos);renderShopping(shopping);}catch(e){toast(e.message)}}
document.querySelectorAll("[data-water]").forEach(button=>button.onclick=async()=>{try{await api("/api/water",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_user_id:userId,ml:Number(button.dataset.water)})});loadTools();}catch(e){toast(e.message)}});
$("workoutForm").addEventListener("submit",async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));data.telegram_user_id=userId;data.duration_minutes=Number(data.duration_minutes);try{await api("/api/workouts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});event.target.reset();event.target.elements.duration_minutes.value=60;toast("Тренировка сохранена");loadTools();}catch(e){toast(e.message)}});
$("measurementForm").addEventListener("submit",async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));data.telegram_user_id=userId;for(const key of ["chest_cm","waist_cm","hips_cm","arm_cm","thigh_cm"])data[key]=data[key]?Number(data[key]):null;try{await api("/api/measurements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});event.target.reset();toast("Замеры сохранены");loadTools();}catch(e){toast(e.message)}});
async function compressImage(file){if(file.size<=1500*1024)return file;try{const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error()),"image/jpeg",.82));}catch{if(file.size<=2*1024*1024)return file;throw new Error("Не удалось уменьшить фото. Выбери изображение до 2 МБ")}}
$("progressPhotoInput").onchange=async event=>{const file=event.target.files[0];if(!file)return;$("progressPhotoName").textContent=file.name;try{const image=await compressImage(file),form=new FormData();form.append("telegram_user_id",userId);form.append("image",image,"progress.jpg");await api("/api/progress-photos",{method:"POST",body:form});toast("Фото прогресса сохранено");event.target.value="";loadTools();}catch(e){toast(e.message)}};
$("feedbackScreenshot").onchange=event=>{$("feedbackFileName").textContent=event.target.files[0]?.name||"Необязательно, до 2 МБ";};
$("feedbackForm").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(),file=event.target.elements.screenshot.files[0];form.append("message",event.target.elements.message.value);try{if(file)form.append("screenshot",await compressImage(file),"screenshot.jpg");await api("/api/feedback",{method:"POST",body:form});event.target.reset();$("feedbackFileName").textContent="Необязательно, до 2 МБ";toast("Сообщение отправлено владельцу");}catch(e){toast(e.message)}});
$("deleteAccount").onclick=async()=>{const confirmation=$("deleteConfirmation").value;if(confirmation.trim().toUpperCase()!=="УДАЛИТЬ")return toast("Сначала напиши слово УДАЛИТЬ");if(!confirm("Удалить профиль и всю историю без возможности восстановления?"))return;try{await api("/api/account",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmation})});toast("Все данные удалены");setTimeout(()=>location.reload(),1000);}catch(e){toast(e.message)}};
function wrapCanvasText(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(" ");let line="",currentY=y;for(const word of words){const test=`${line}${word} `;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line.trim(),x,currentY);line=`${word} `;currentY+=lineHeight;}else line=test;}if(line)ctx.fillText(line.trim(),x,currentY);return currentY;}
$("shareReport").onclick=async()=>{const button=$("shareReport"),old=button.textContent;button.disabled=true;button.textContent="Создаю…";try{const [insights,profile]=await Promise.all([api("/api/insights"),api("/api/profile")]),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=1080;canvas.height=1350;const gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,"#14251d");gradient.addColorStop(1,"#355944");ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);ctx.fillStyle="#b9f24a";ctx.font="700 34px Arial";ctx.fillText("MASSUP AI · НЕДЕЛЬНЫЙ ПРОГРЕСС",70,105);ctx.fillStyle="#fff";ctx.font="800 76px Arial";wrapCanvasText(ctx,`${profile.name}, так держать!`,70,220,900,90);ctx.fillStyle="#c8d4cc";ctx.font="400 30px Arial";ctx.fillText(new Date().toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"}),70,330);const cards=[["Серия",`${insights.streak_days} дней`],["Дневник",`${insights.week.days_logged} из 7 дней`],["Среднее",`${Math.round(insights.week.averages.kcal)} ккал`],["Изменение веса",`${insights.week.weight_change_kg>0?'+':''}${insights.week.weight_change_kg} кг`]];cards.forEach(([label,value],i)=>{const x=70+(i%2)*475,y=420+Math.floor(i/2)*235;ctx.fillStyle="#ffffff12";ctx.beginPath();ctx.roundRect(x,y,430,185,28);ctx.fill();ctx.fillStyle="#b9f24a";ctx.font="700 28px Arial";ctx.fillText(label,x+28,y+50);ctx.fillStyle="#fff";ctx.font="800 49px Arial";ctx.fillText(value,x+28,y+125);});ctx.fillStyle="#fff";ctx.font="700 39px Arial";ctx.fillText(`Уровень ${insights.gamification.level} · ${insights.gamification.level_name}`,70,970);ctx.fillStyle="#c8d4cc";ctx.font="400 29px Arial";wrapCanvasText(ctx,insights.forecast.message,70,1035,900,42);ctx.fillStyle="#b9f24a";ctx.font="700 27px Arial";ctx.fillText("Питание и прогресс под контролем",70,1255);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png")),file=new File([blob],"massup-week.png",{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:"Мой прогресс MassUp AI",files:[file]});else{const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=file.name;link.click();toast("Карточка сохранена");}}catch(e){if(e.name!=="AbortError")toast(e.message)}finally{button.disabled=false;button.textContent=old;}};
async function viewFeedbackScreenshot(id){try{const blob=await protectedBlob(`/api/admin/feedback/${id}/screenshot`),url=URL.createObjectURL(blob);window.open(url,"_blank");}catch(e){toast(e.message)}}
$("broadcastForm").elements.audience.onchange=async event=>{try{const result=await api(`/api/admin/broadcast/estimate?audience=${event.target.value}`);$("broadcastEstimate").textContent=`Получателей: ${result.recipients}`;}catch(e){toast(e.message)}};
$("broadcastForm").addEventListener("submit",async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));data.confirmed=event.target.elements.confirmed.checked;if(!data.confirmed)return toast("Подтверди отправку рассылки");if(!confirm("Отправить это сообщение выбранным пользователям?"))return;const button=event.submitter,old=button.textContent;button.disabled=true;button.textContent="Отправляю…";try{const result=await api("/api/admin/broadcast",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});toast(`Отправлено: ${result.sent}, ошибок: ${result.failed}`);event.target.reset();loadAdmin();}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent=old;}});

$("todayDate").textContent=new Intl.DateTimeFormat("ru-RU",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
if(location.hash==="#tools")switchView("toolsView");
discoverAdmin();loadProfile();loadDashboard();
